<?php

declare(strict_types=1);

require_once __DIR__ . '/inc/db.php';
require_once __DIR__ . '/inc/view.php';

$id = isset($_GET['id']) ? (int)$_GET['id'] : 0;
if ($id <= 0) {
    http_response_code(404);
    echo 'Not found';
    exit;
}

$stmt = db()->prepare(
  "SELECT id, is_published, pdf_original_name, pdf_stored_name
     FROM announcements
     WHERE id = ?
     LIMIT 1"
);
$stmt->execute([$id]);
$row = $stmt->fetch();

if (!$row || (int)$row['is_published'] !== 1) {
    http_response_code(404);
    echo 'Not found';
    exit;
}

$stored = (string)($row['pdf_stored_name'] ?? '');
if ($stored === '') {
    http_response_code(404);
    echo 'Not found';
    exit;
}

// Prevent path traversal (stored name should be generated by server).
if (!preg_match('/^[A-Za-z0-9._-]+$/', $stored)) {
    http_response_code(400);
    echo 'Bad request';
    exit;
}

$path = rtrim(UPLOAD_DIR, '/\\') . '/' . $stored;
if (!is_file($path)) {
    http_response_code(404);
    echo 'Not found';
    exit;
}

$downloadName = (string)($row['pdf_original_name'] ?? 'dokumen.pdf');
$downloadName = $downloadName !== '' ? $downloadName : 'dokumen.pdf';

header('Content-Type: application/pdf');
header('X-Content-Type-Options: nosniff');
header('Content-Disposition: inline; filename="' . str_replace('"', '', $downloadName) . '"');
header('Content-Length: ' . (string)filesize($path));

readfile($path);
exit;
